spring.application.name=dassco_test_suite

fileproxy.url=${FILEPROXY_LOCATION:https://dassco.dk/file_proxy/api}
assetservice.url=${ASSETSERVICE_LOCATION:https://dassco.dk/ars/api}
assetservice.health=${ASSETSERVICE_HEALTH:https://dassco.dk/ars}
keycloak.hostname=${KEYCLOAK_LOCATION:https://dassco.dk/keycloak}

spring.config.import=optional:file:./application-local.properties

test-asset=test-suite-main-asset

client.id=${CLIENT_ID:clientid}
client.secret=${CLIENT_SECRET:clientsecret}

read.role.1.client.id=${READ_ROLE_1_CLIENT_ID:readrole1clientid}
read.role.1.client.secret=${READ_ROLE_1_CLIENT_SECRET:readrole1clientsecret}

write.role.1.client.id=${WRITE_ROLE_1_CLIENT_ID:writerole1clientid}
write.role.1.client.secret=${WRITE_ROLE_1_CLIENT_SECRET:writerole1clientsecret}